# Generated by Django 2.0.6 on 2018-06-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
