# Generated by Django 2.0.6 on 2018-06-18 20:47

from django.db import migrations, transaction


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    person_model = apps.get_model('persons', 'Person')
    with transaction.atomic():
        # If Person model is big (say 100,000+ records)
        # you might want to split this transaction into chunks
        for person in person_model.objects.all():
            # .save() will trigger pre_save signal handler:
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_full_name'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
