# Generated by Django 2.0.6 on 2018-06-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_full_name_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
